import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import PencilBanner from "./components/PencilBanner";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import GoogleCaptchaWrapper from "./api/verifyRecaptcha/GoogleCaptchaWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleCaptchaWrapper>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-rows-[auto_1fr_auto] min-h-screen">
          {/* Header */}
          <Header>
            <PencilBanner
              ctaAction="/estimate"
            />
            <Nav />
          </Header>

          {/* Main content */}
          <main className="pb-20">{children}</main>


          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
    </GoogleCaptchaWrapper>

  );
}
