import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import PencilBanner from "./components/PencilBanner";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import GoogleCaptchaWrapper from "./api/verifyRecaptcha/GoogleCaptchaWrapper";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import Script from "next/script";
import { GoogleAnalytics } from "@next/third-parties/google";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App yo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
    <html lang="en">
      <GoogleAnalytics gaId="AW-1016197559" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <GoogleCaptchaWrapper>
    <SpeedInsights />
    <Analytics />
        <div className="grid grid-rows-[auto_1fr_auto] min-h-screen">
          {/* Header */}
          <Header>
            <PencilBanner
              ctaAction="/estimate"
            />
            <Nav />
          </Header>

          {/* Main content */}
          <main>{children}</main>

          {/* Footer */}
          <Footer />
        </div>
        </GoogleCaptchaWrapper>
      </body>
    </html>
  );
}
